// Overall Site Layout File like Index.html

// ------------- Imports ------------------
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"; // vercel analytics
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";

// ------------ Font Styles ---------------
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ---------------- Site Meta Data -----------------
export const metadata: Metadata = {
  title: "Anixo",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Header />
        {children}
        <Analytics />
        <Footer />

      </body>
    </html >
  );
}
